$(document).ready(function () {

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "The Abysswalker", minLevel: "Starting", name: "Marked By The Abyss", move: "The abyss has left its mark on you and you suffer some form of physical debilitation, the GM will tell you the specifics. In exchange, once per battle you may simply deal your damage to a foe of your choice, using the power of the abyss to catch them off-guard.", preamble: "When you walk the abyss and it affects you permanently you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "The Abysswalker", minLevel: "2", name: "Abysswalking", move: "When you lead someone through the abyss, roll +WIS. On a 10+, you safely exit the abyss at wherever you were trying to go. On a 7-9, you get out of the abyss unharmed, but in a place you've never been before. On a 6-, as 7-9 but you drag something big and nasty out of the abyss with you.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "The Abysswalker", minLevel: "2", name: "By Absence Sustained", move: "When a move tells you to mark off rations, ignore it. The abyss provides your sustenance now.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "The Abysswalker", minLevel: "2", name: "The Abyss Gazes Also", move: "When someone Discerns Realities about you or otherwise studies or observes you intently, you may ask a single question from the Discern Realities list about them.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Alienist", minLevel: "Starting", name: "Incite Insanity", move: "When you reveal a secret man was not meant to know to someone, roll +Cha. On a 10+ they go mad as what they thought was reality falls apart, on a 7-9 your words cause them to panic and lash out at you in a moment of primal fear, on a 6- even you were unprepared for this revelation, and you are temporarily driven insane.", preamble: "When you make a pact with the incomprehensible (and quite possibly non-euclidean) beings that lurk outside of reality, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Alienist", minLevel: "2", name: "Mad Whispers", move: "When you take a moment to listen to the maddening whispers that always buzz at the back of your mind, you take +1 to Spout Lore.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Alienist", minLevel: "2", name: "Impossible Geometry", move: "When you are hopelessly lost and call upon the alien energies coursing through your mind, roll +Int. On a 10+, no matter which way you go you'll make progress towards your destination. On a 7-9, you get out, but not where (or even when) you wanted. On a 6-, you end up somewhere nasty, or come out at just the wrong time.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Alienist", minLevel: "2", name: "Twisted Form", move: "Your body has been warped and twisted by the being you've entered a pact with. Choose 1, the GM will tell you how your body has been horrifically altered to make it happen.<ul><li>Your body counts as a weapon with the /messy/ tag.</li><li>You gain +1 armor.</li><li>You cannot be surprised or caught off guard anymore.</li></ul>", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Alienist", minLevel: "2", name: "Rats In The Walls", move: "When you cause someone to hear or see something that isn't there, roll +Cha. On a 10+ they accept it, no matter what it may be. On a 7-9 they only experience part of the hallucination, the GM decides what gets through and what doesn't.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ ["RacePanel", { source: "Emong's DW Stuff", name: "Automaton", subPanels: [ ["RaceClassPanel", {className: "*", move: "<dl class='moves'><dt>By Iron Sustained</dt><dd>If a move tells you to mark off rations, ignore it. You're a robot, why would you need to eat?</dd><dt>Metal Man</dt><dd>You can't be healed by mundane or magical means; instead, you or someone else can perform repairs on you whenever you Make Camp or Recover, letting you heal as normal. Additionally, when you take a Last Breath and roll a 7-9, you deactivate and go into standby mode until someone can repair you, the GM will tell you what that'll require.</dd></dl>" } ] ] } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Automaton", minLevel: "Starting", name: "Modular Chassis", move: "When you Make Camp and spend time modifying yourself, choose two stats. You take +1 ongoing to all rolls using one of them, and -1 ongoing to all rolls using the other until you spend time modifying yourself again.", preamble: "When you are an automaton and you spend time attempting to upgrade yourself, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Automaton", minLevel: "2", name: "Integrated Weaponry", move: "When you integrate a single weapon into your body, choose 1.<ul class='checklist'><li>The weapon can extend or retract into you slightly, give it one more range tag.</li><li>The weapon can fold into a compartment in your body and be completely hidden from sight.</li><li>You devise a system to make the weapon hit harder, giving it the /forceful/ tag.</li></ul>", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Automaton", minLevel: "2", name: "Clockwork Repairman", move: "When you attempt to repair a piece of advanced or complex machinery, roll +Int. On a 10+ you get it into perfect condition, on a 7-9 it's working, but there's a few problems with it that the GM will make apparent, on a 6- you've left it in worse condition than when you started.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Automaton", minLevel: "2", name: "Mechanical Perfection", move: "At the start of the session, roll +nothing. On a 10+ hold 3, on a 7-6 hold 2, and on a 6- hold 1. You may spend this hold one at a time to give any roll you make a +1, using cold machine logic and precision to help ensure success.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Automaton", minLevel: "2", name: "Get Equipped With", move: "When you harvest an enemy for parts, roll +Con. On a 10+ hold 3, on a 7-9 hold 2, and on a 6- hold 1. You may spend one hold to make a move that the enemy you harvested had, the GM will tell you which one you got. You can only have one of these moves at a time, and once you're out of hold you lose the move.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Beast Hunter", minLevel: "Starting", name: "Beastcraft", move: "When you craft a melee weapon from parts of monsters, roll +Str. On a 10+, choose 2. On a 7-9, choose 1. Describe how you achieve what you choose and pick /hand/, /close/, or /reach/ as its range.<ul><li>The weapon has the /precise/ tag.</li><li>The weapon has the /messy/ tag and does +1 damage.</li><li>The weapon has 1 piercing.</li></ul>", preamble: "When you a hunt a giant monster and make use of its remains, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Beast Hunter", minLevel: "2", name: "Advanced Craftsmanship", move: "When you craft a melee weapon from parts of monsters and have access to advanced tools, add these to the list you can choose from.<ul><li>You may use the weapon to Volley.</li><li>The weapon gives +1 armor to those trained in its use.</li><li>The weapon can be loaded with a dose of poison that can be injected on a hit.</li></ul>", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Beast Hunter", minLevel: "2", name: "Hidecraft", move: "When you craft a suit of armor from animal parts, roll +Str. On a 10+, choose 2. On a 7-9 choose 1.<ul><li>The armor is flexible and does not have the /clumsy/ tag.</li><li>The armor gives 2-armor instead of 1-armor.</li></ul>", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Beast Hunter", minLevel: "2", name: "Big Game Hunter", move: "When you attack a giant monster with intent to harvest its parts, take +1 ongoing against it.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Dilettante", minLevel: "Starting", name: "Been There, Done That", move: "You've experienced more than most could ever dream of, and quite frankly you don't have time to do it again. When others would be surprised or frightened (even due to some supernatural effect), you're just bored.", preamble: "When you feel like you've seen it all, and disregard your own safety just to experience something new, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Dilettante", minLevel: "2", name: "There And Back Again", move: "You've slipped through Death's fingers more than is probably healthy, but you're getting pretty good at it. When take your Last Breath and roll a 10+ take +1-hold. You may spend this hold to take +hold spent forward on a Last Breath.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Dilettante", minLevel: "2", name: "This Reminds Me Of That Time When...", move: "When you stop for a while to reminisce about a similar situation while you're in the middle of something risky, take +1 ongoing on rolls to resolve your current problem.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Dilettante", minLevel: "2", name: "One Weird Trick", move: "All your experiences have taught you a lot of little tricks that aren't exactly common knowledge. You gain a move from another compendium class (subject to GM approval, of course).", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ ["RacePanel", { source: "Emong's DW Stuff", name: "Dragon", subPanels: [ ["RaceClassPanel", {className: "*", move: "<dl class='moves'><dt>Bottomless Stomach</dt><dd>When a move tells you to mark off rations, mark off one more than you usually would.</dd><dt>Dragonic Transformation</dt><dd>You may transform between your natural dragon form and a humanoid form at will. As a dragon your teeth, claws, and breath weapon (element of your choice) all deal class damage and you may fly. You have access to all of your moves as a dragon, though some may be harder to perform. A dragon is going to have a hard time playing an instrument or using a shield, for instance, and may not fit into all buildings. You select the general appearance and race of your humanoid form the first time you transform into it during play, but no matter what there will always be at least one thing about it that is imperfect, be it the way you move, having cat-like reptilian eyes, or whatever. Tell the GM what your imperfection is.</dd></dl>" } ] ] } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Great Wyrm", minLevel: "Starting", name: "Sleep On A Pile Of Gold", move: "Whenever you add 100 gold to your hoard, take +1 hold. You may spend this hold (and by extension, your hoard) you gain +hold spent forward to Parley, or otherwise convince someone to do something.", preamble: "When you are a dragon, and you knowingly sacrifice or allow significant harm to come to something or someone important to you in the name of avarice you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Great Wyrm", minLevel: "2", name: "Dragon Magic", move: "If you don't have the Ritual move, you gain it as per the Wizard class except that you may choose to roll either +Int or +Cha when you use it. If you do have the Ritual move, choose any one spell you know. You now prepare that spell as though it were one level lower, and can memorize it even without having access to your spellbook.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Great Wyrm", minLevel: "2", name: "Burninating The Countryside", move: "Your breath weapon uses a damage die one step higher than your class damage (1d4 &rarr; 1d6 &rarr; 1d8 &rarr; 1d10 &rarr; 2d6)", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Great Wyrm", minLevel: "2", name: "Serpentine Tongue", move: "When you Discern Realities about a person, you may also ask \"What is it they desire most?\"", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Great Wyrm", minLevel: "2", name: "The Superior Species", move: "When you Spout Lore while exaggerating or overemphasizing the importance of dragons and their history in that lore, take +1 to the roll.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Drunken Master", minLevel: "Starting", name: "Drink Like A Fish", move: "When you take a swig of an alcoholic drink, roll +Con. On a 10+ you now have 3 drunkenness. On a 7-9, you have 2 drunkenness. On a 6- you have 1. You may reduce your drunkenness by one at any time to heal yourself of 1d4 damage.", preamble: "When you go on a three day drunken bender, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Drunken Master", minLevel: "2", name: "Ethanol Powered", move: "Choose either Hack And Slash or Cast A Spell, if you have it. From now on whenever you use the move you picked roll +drunkenness instead of what the move says.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Drunken Master", minLevel: "2", name: "Lightweight", move: "When you take a drink you gain +1 drunkenness on top of whatever your roll gives you.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Drunken Master", minLevel: "2", name: "Seeing Double", move: "When you Defy Danger by stumbling and lurching out of the way, roll +drunkness instead of a stat.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Drunken Master", minLevel: "2", name: "Iron Liver", move: "When you drink from a poisoned cup, you may ignore the effects of the poison. After what you do to your body every day there's not a lot poison can do to it anymore.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Ever-Shifter", minLevel: "Starting", name: "Fluidity Of Form", move: "When you will your body to take on an aspect (wings, claws, etc.) of a form you've previously assumed, roll +Con. On a 10+ choose 3, on a 7-9 choose 2, and on a 6- choose 1.<ul><li>The transformation is quick and painless</li><li>You can be sure of how long the transformation will last</li><li>You can be certain that the aspect will not have any flaws</li></ul>", preamble: "When you come to rely on transformative magic to solve problems, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Ever-Shifter", minLevel: "2", name: "Flesh As Clay", move: "You may now use Fluidity Of Form to take on aspects of forms you have never assumed before.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Ever-Shifter", minLevel: "2", name: "Impart Instability", move: "When you touch someone and will them to change, roll +Con. On a 10+, you may change them as though you had rolled a 10+ on Fluidity Of Form. On a 7-9, the change slips from your control, causing them to change completely at random. On a 6-, as a 7-9 except the magic surges back into you, and you suffer the effects.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Geomancer", minLevel: "Starting", name: "One With The Land", move: "Choose an environment to devote yourself to. When you take this move, and every time you take another Geomancer move, your body develops an aspect of an animal that lives in your environment (a bear's pelt or a moose's antlers, for example). Your GM will give you a move based on that aspect that you can perform at will.", preamble: "When you devote yourself wholly to an environment and draw your power from it, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Geomancer", minLevel: "2", name: "Going Green", move: "Choose a move. When features of your chosen environment give you an unexpected advantage in using that move, you take +1 ongoing to any rolls that move involves. You may take Going Green as many times as you want, so long as you choose a different move for it to affect every time.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Geomancer", minLevel: "2", name: "Home Away From Home", move: "When you force the land to change into your chosen environment, roll +Wis. On a 10+, the area around you changes into your environment, be it a desert, a lake, or whatever for the next day or so. On a 7-9, it changes but you failed to properly appease the local spirits when doing it.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Geomancer", minLevel: "2", name: "Call Of The Wilds", move: "When you call for animal assistance, roll +Cha. On a 10+, the horde of animals from your environment that appears will listen to you so long as you're not telling them to do something obviously suicidal. On a 7-9, you'll just have to hope they do something helpful. On a 6-, something unwelcome hears the call.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Mystic Theurge", minLevel: "Starting", name: "Dichotomy Defied", move: "If you are a Wizard, you gain access to the Divine Guidance move (as well as a Diety) as per the Cleric class. If you are a Cleric, you gain access to the Spell Defence move as per the Wizard class.", preamble: "When you are a Wizard or a Cleric, and spend significant time studying the other side of magic you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Mystic Theurge", minLevel: "2", name: "Melding Of Magics", move: "Add a single spell of your level or lower from another class's spell list to yours (and to your spellbook, if appropriate). You may take this move as many times as you like.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Mystic Theurge", minLevel: "2", name: "Interdisciplinary Study", move: "If you are a Wizard, choose one move from the Cleric class list. If you're a Cleric, choose one from the Wizard class list.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Mystic Theurge", minLevel: "2", name: "Well-Reasoned Faith", move: "When you spend time studying ancient religous and magical texts, take +1 forward to Spout Lore.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Mystic Theurge", minLevel: "2", name: "Crossing The Streams", move: "When you attempt to combine arcane and divine energy to cast a spell, roll +Int or +Wis, whichever is higher. On a 10+ the spell is empowered, and you may add your level to any damage dealt or healed by the spell and increase the spell's targets by one. On a 7-9, the spell is empowered, but your diety is offended by the mixing of holy and mortal magics and requires some form of penance from you. On a 6- you screw it up completely, the GM will tell you the consequences of your folly.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Skinwalker", minLevel: "Starting", name: "Walk Like The Animals", move: "When you wear the skin of a dangerous animal into battle, it imparts a portion of its hunting tactics upon you, granting your attacks +1 piercing.", preamble: "When you wear the skin of an animal as an intimidation tactic in a fight, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Skinwalker", minLevel: "2", name: "Talk Like The Animals", move: "When you are wearing the skin of an animal, you gain the ability to speak with animals as easily as you speak with people. The animals will perceive you as whichever animals' skin you're wearing.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Skinwalker", minLevel: "2", name: "Borrowed Savagery", move: "When you attack while wearing the skin of a dangerous animal, you do +1d4 damage as the feral nature of the animal rushes through your mind.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Skinwalker", minLevel: "2", name: "Become The Beast", move: "You gain the Shapeshifter move as per the Druid class, except that it may only be used to shift into the form of whatever animals' skin you're wearing.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Devotee of the Spider-Mother", minLevel: "Starting", name: "Touch The World-Thread", move: "When you take a moment to meditate on the world-spanning webs of the Spider-Mother, roll +Wis. On a 10+, the GM will give you a vision of something that will soon come to pass. On a 7-9, the GM will give you a general feeling of either good or bad about the future, but no details.", preamble: "When you are a werespider and are granted the favor of the Spider-Mother, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Devotee of the Spider-Mother", minLevel: "2", name: "Arachnid Stealth", move: "When you hold completely still in a dark area, enemies will never spot you until you move.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Devotee of the Spider-Mother", minLevel: "2", name: "Envenomed Fangs", move: "At the start of each day, roll +Con. On a 10+, hold 3. On a 7-9, hold 2. On a 6-, hold 1. You may spend this hold one at a time to deliver your poison on a successful bite.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Devotee of the Spider-Mother", minLevel: "2", name: "Arachnophobia", move: "When you shift into your spider form, roll +Cha. On a 10+, any enemies that see you transform are terrified, frozen in place for a few moments. On a 7-9, they're scared, but all that screaming is going to attract some attention to you.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Lord of Arcadia", minLevel: "Starting", name: "Oathbound", move: "When you swear a solemn oath with someone, it is empowered by your fae nature. Both of you get +1 ongoing on actions to keep your oath, and must Defy Danger if you break it.", preamble: "When you are one of the fae and consistently act in an overly dramatic manner, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Lord of Arcadia", minLevel: "2", name: "The Brothers Grimm", move: "When you spin a fantastic and wonderous tale, roll +Cha. On a 10+, the story comes to life, in a sense. People around you will assume roles in the story and act it out as you tell it. On a 7-9, people will act out your story, but they'll break free of their role if the character does something they wouldn't do. On a 6-, your words tap into a more primal magic. The central conflict of your story manifests in reality, poised against you.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Lord of Arcadia", minLevel: "2", name: "Namebearer", move: "When you bequeath a title to someone for their accomplishments, roll +Cha. On a 10+, they hold 3. On a 7-9, they hold 1. On a 6- the title falls flat, ringing false to any that hear it. They may spend this hold one for one to do one of the following.<ul><li>Make a pact or oath sworn on their title magically binding.</li><li>Gain +2 forward to do something related to their title.Instantly convince someone of their title's (and accomplishment's) veracity.</li></ul>", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Lord of Arcadia", minLevel: "2", name: "Fickle Nature", move: "Once per session when you act in a manner contradictory to your alignment, you may shift your alignment by one step.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "Lord of Arcadia", minLevel: "2", name: "The World's A Stage", move: "When you shapeshift into a humanoid disguise, roll +Con. On a 10+ choose 2, on a 7-9 choose 1.<ul><li>You have normal feet for your form.</li><li>Your form casts a shadow that matches its appearance.</li><li>You can speak without rhyming.</li></ul>", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "The Inked", minLevel: "Starting", name: "Enchanted Ink", move: "Select an arcane spell that is of 3rd level or lower; this spell is stored in your tattoo. You can change this spell if you can find a competent magical tattooist to alter your tattoo. When you invoke the power of your tattoo, roll +Con. On a 10+ the spell stored in your tattoo is cast. On a 7-9, the spell is cast but your tattoo is drained and cannot be invoked again until it you Make Camp and can recharge it. When you recharge your tattoo, roll+Wis. On a 10+ hold 2, on a 7-9 hold 1, on a 6- hold 1, but magical energy leaks from your tattoo into the world around you, your GM will tell you what that means. You may spend this hold at any time to recharge your tattoo immediately.", preamble: "When you get a tattoo containing magical power inked onto your skin, you may take this move when you level up.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "The Inked", minLevel: "2", name: "Runic Wards", move: "When your tattoo is charged and clearly on display, and you aren't wearing armor (not counting shields), you count as having 2 armor.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "The Inked", minLevel: "2", name: "Searing Brand", move: "When you deal damage, you may choose to drain your tattoo to increase the damage you deal by your level.", prerequisiteType: "None", prerequisite: "" } ] ]);

    $.addSourceData([ [ "ClassMovePanel", {source: "Emong's DW Stuff", className: "The Inked", minLevel: "2", name: "Intricate Design", move: "When you have additional magical symbols added to your tattoo, you may store another arcane spell that is of 3rd level or lower in your tattoo. You can choose which of your spells you cast using Enchanted Ink, but once your tattoo is drained, it's drained and you won't be able to cast either spell until you recharge it.", prerequisiteType: "None", prerequisite: "" } ] ]);

});
